// src/app/components/seat-booking/seat-booking.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-seat-booking',
  templateUrl: './seat-booking.component.html',
  styleUrls: ['./seat-booking.component.scss']
})
export class SeatBookingComponent {
  @Output() confirm = new EventEmitter<{seats: string[], total: number}>();

  rows = 6;
  cols = 10;
  basePrice = 200;
  priceIncrement = (800 - 200) / (this.rows - 1);
  
  selectedSeats = new Set<string>();
  bookedSeats = new Set<string>();

  constructor() {
    this.generateBookedSeats();
  }

  private generateBookedSeats(): void {
    const bookedCount = 15;
    const seatKeys: string[] = [];
    
    for (let r = 0; r < this.rows; r++) {
      for (let c = 0; c < this.cols; c++) {
        seatKeys.push(`${r}-${c}`);
      }
    }

    for (let i = 0; i < bookedCount; i++) {
      const index = (i * 37 + 13) % seatKeys.length;
      if (!this.bookedSeats.has(seatKeys[index])) {
        this.bookedSeats.add(seatKeys[index]);
      } else {
        for (let j = 1; j < seatKeys.length; j++) {
          const nextIndex = (index + j) % seatKeys.length;
          if (!this.bookedSeats.has(seatKeys[nextIndex])) {
            this.bookedSeats.add(seatKeys[nextIndex]);
            break;
          }
        }
      }
    }
  }

  getSeatRows(): number[] {
    return Array(this.rows).fill(0).map((_, i) => i);
  }

  getSeatCols(): number[] {
    return Array(this.cols).fill(0).map((_, i) => i);
  }

  toggleSeat(row: number, col: number): void {
    const seatId = `${row}-${col}`;
    if (this.bookedSeats.has(seatId)) return;

    if (this.selectedSeats.has(seatId)) {
      this.selectedSeats.delete(seatId);
    } else {
      this.selectedSeats.add(seatId);
    }
  }

  isSeatSelected(row: number, col: number): boolean {
    return this.selectedSeats.has(`${row}-${col}`);
  }

  isSeatBooked(row: number, col: number): boolean {
    return this.bookedSeats.has(`${row}-${col}`);
  }

  getPriceForSeat(row: number): number {
    return this.basePrice + row * this.priceIncrement;
  }

  getSeatClass(row: number, col: number): string {
    const seatId = `${row}-${col}`;
    const price = this.getPriceForSeat(row);
    
    if (this.bookedSeats.has(seatId)) {
      return 'seat booked';
    } else if (this.selectedSeats.has(seatId)) {
      return 'seat selected';
    } else if (price < 400) {
      return 'seat cheap';
    } else if (price >= 400 && price < 600) {
      return 'seat medium';
    } else {
      return 'seat expensive';
    }
  }

  getTotalPrice(): number {
    let total = 0;
    for (const seatId of this.selectedSeats) {
      const [rowStr] = seatId.split('-');
      const row = parseInt(rowStr, 10);
      total += this.getPriceForSeat(row);
    }
    return total;
  }

  onConfirmBooking(): void {
    this.confirm.emit({
      seats: Array.from(this.selectedSeats),
      total: this.getTotalPrice()
    });
  }
}
<div class="seat-booking-container">
  <div class="screen-indicator">
    <div class="screen-line"></div>
    <div class="screen-label">SCREEN</div>
  </div>

  <div class="price-gradient">
    <span class="price-label">₹{{ basePrice }}</span>
    <div class="gradient-bar"></div>
    <span class="price-label">₹{{ basePrice + priceIncrement * (rows - 1) }}</span>
  </div>

  <div class="seats-grid">
    <div *ngFor="let row of getSeatRows()" class="seat-row">
      <div *ngFor="let col of getSeatCols()" 
           class="seat-container"
           [class.aisle-gap]="col === 2 || col === 7">
        <button 
          mat-icon-button 
          [class]="getSeatClass(row, col)"
          [disabled]="isSeatBooked(row, col)"
          (click)="toggleSeat(row, col)">
          <mat-icon>event_seat</mat-icon>
        </button>
      </div>
    </div>
  </div>

  <div class="legend">
    <div class="legend-item">
      <mat-icon class="seat cheap">event_seat</mat-icon>
      <span>₹200-₹399</span>
    </div>
    <div class="legend-item">
      <mat-icon class="seat medium">event_seat</mat-icon>
      <span>₹400-₹599</span>
    </div>
    <div class="legend-item">
      <mat-icon class="seat expensive">event_seat</mat-icon>
      <span>₹600-₹800</span>
    </div>
    <div class="legend-item">
      <mat-icon class="seat selected">event_seat</mat-icon>
      <span>Selected</span>
    </div>
    <div class="legend-item">
      <mat-icon class="seat booked">event_seat</mat-icon>
      <span>Booked</span>
    </div>
  </div>

  <div class="booking-summary">
    <div class="summary-info">
      <p><strong>{{ selectedSeats.size }}</strong> Seats Selected</p>
      <p class="total-price headline-font">₹{{ getTotalPrice().toFixed(2) }}</p>
    </div>
    <button 
      mat-raised-button 
      color="primary" 
      [disabled]="selectedSeats.size === 0"
      (click)="onConfirmBooking()">
      Confirm Booking
    </button>
  </div>
</div>

// src/components/seat-booking.tsx
'use client';

import { useState, useMemo, useEffect } from 'react';
import { Armchair } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

const rows = 6;
const cols = 10;
const basePrice = 200;
const priceIncrement = (800 - 200) / (rows - 1);

const generateBookedSeats = () => {
  const seats = new Set<string>();
  const bookedCount = 15;
  const seatKeys = [];
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      seatKeys.push(`${r}-${c}`);
    }
  }

  for (let i = 0; i < bookedCount; i++) {
    const index = (i * 37 + 13) % seatKeys.length;
    if (!seats.has(seatKeys[index])) {
      seats.add(seatKeys[index]);
    } else {
        for (let j = 1; j < seatKeys.length; j++){
            const nextIndex = (index + j) % seatKeys.length
            if (!seats.has(seatKeys[nextIndex])) {
                seats.add(seatKeys[nextIndex])
                break;
            }
        }
    }
  }
  return seats;
};

const getPriceForSeat = (row: number) => {
  return basePrice + row * priceIncrement;
};

export default function SeatBooking() {
  const [selectedSeats, setSelectedSeats] = useState<Set<string>>(new Set());
  const [bookedSeats, setBookedSeats] = useState<Set<string>>(new Set());

  useEffect(() => {
    setBookedSeats(generateBookedSeats());
  }, []);

  const toggleSeat = (row: number, col: number) => {
    const seatId = `${row}-${col}`;
    if (bookedSeats.has(seatId)) return;

    const newSelectedSeats = new Set(selectedSeats);
    if (newSelectedSeats.has(seatId)) {
      newSelectedSeats.delete(seatId);
    } else {
      newSelectedSeats.add(seatId);
    }
    setSelectedSeats(newSelectedSeats);
  };

  const totalPrice = useMemo(() => {
    let total = 0;
    for (const seatId of selectedSeats) {
      const [rowStr] = seatId.split('-');
      const row = parseInt(rowStr, 10);
      total += getPriceForSeat(row);
    }
    return total;
  }, [selectedSeats]);

  const totalSelected = selectedSeats.size;

  return (
    <Card className="bg-card/50">
      <CardContent className="p-6 flex flex-col items-center gap-6">
        <div className="w-full max-w-md">
           <div className="h-1 w-full bg-muted-foreground rounded-full mb-2 opacity-50" />
           <div className="h-4 w-full bg-muted-foreground rounded-b-xl mb-1 text-center text-xs font-bold text-background flex items-center justify-center">SCREEN</div>
        </div>

        <div className="w-full flex items-center gap-4">
          <span className='text-sm text-muted-foreground whitespace-nowrap'>₹{basePrice}</span>
          <div className='w-full h-2 rounded-full bg-gradient-to-r from-green-400 to-red-500' />
          <span className='text-sm text-muted-foreground whitespace-nowrap'>₹{basePrice + priceIncrement * (rows - 1)}</span>
        </div>

        <div className="grid gap-2" style={{ gridTemplateColumns: `repeat(${cols}, 1fr)` }}>
          {Array.from({ length: rows }).map((_, row) =>
            Array.from({ length: cols }).map((_, col) => {
              const seatId = `${row}-${col}`;
              const isSelected = selectedSeats.has(seatId);
              const isBooked = bookedSeats.has(seatId);
              const price = getPriceForSeat(row);
              
              let colorClass = 'text-muted-foreground/80 hover:text-primary';
              if (price < 400) {
                colorClass = 'text-green-400 hover:text-green-300';
              } else if (price >= 400 && price < 600) {
                colorClass = 'text-yellow-400 hover:text-yellow-300';
              } else {
                colorClass = 'text-red-400 hover:text-red-300';
              }

              return (
                <div
                  key={seatId}
                  className="relative flex justify-center items-center"
                  style={col === 2 || col === 7 ? { marginRight: '1rem' } : {}}
                >
                  <Armchair
                    onClick={() => toggleSeat(row, col)}
                    className={cn(
                      'w-6 h-6 transition-colors duration-200',
                       isBooked
                        ? 'text-muted-foreground/50 fill-muted-foreground/30 cursor-not-allowed'
                        : `${colorClass} cursor-pointer`,
                       isSelected && 'text-accent fill-accent/50'
                    )}
                  />
                </div>
              );
            })
          )}
        </div>

        <div className="flex justify-center gap-6 text-sm text-muted-foreground">
          <div className="flex items-center gap-2">
            <Armchair className="w-5 h-5 text-green-400" />
            <span>₹200-₹399</span>
          </div>
           <div className="flex items-center gap-2">
            <Armchair className="w-5 h-5 text-yellow-400" />
            <span>₹400-₹599</span>
          </div>
           <div className="flex items-center gap-2">
            <Armchair className="w-5 h-5 text-red-400" />
            <span>₹600-₹800</span>
          </div>
          <div className="flex items-center gap-2">
            <Armchair className="w-5 h-5 text-accent fill-accent/50" />
            <span>Selected</span>
          </div>
          <div className="flex items-center gap-2">
            <Armchair className="w-5 h-5 text-muted-foreground/50 fill-muted-foreground/30" />
            <span>Booked</span>
          </div>
        </div>

        <div className="w-full border-t border-border pt-4 mt-4 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div>
            <p className="text-lg">
              <span className="font-bold">{totalSelected}</span> Seats Selected
            </p>
            <p className="text-2xl font-bold font-headline text-primary">₹{totalPrice.toFixed(2)}</p>
          </div>
          <Button size="lg" disabled={totalSelected === 0} className="w-full sm:w-auto">
            Confirm Booking
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
